#include "Framework.h"
#include "VertexType.h"

D3D11_INPUT_ELEMENT_DESC VertexColor::descs[]
{
    {"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT,    0,
    0, D3D11_INPUT_PER_VERTEX_DATA, 0},

    {"COLOR",    0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0,
    D3D11_APPEND_ALIGNED_ELEMENT, D3D11_INPUT_PER_VERTEX_DATA, 0}
};

D3D11_INPUT_ELEMENT_DESC VertexTexture::descs[]
{
    {"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT,    0,
    0, D3D11_INPUT_PER_VERTEX_DATA, 0},

    {"TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT, 0,
    D3D11_APPEND_ALIGNED_ELEMENT, D3D11_INPUT_PER_VERTEX_DATA, 0}
};

/*
typedef struct D3D11_INPUT_ELEMENT_DESC
    {
    LPCSTR SemanticName;
    UINT SemanticIndex;
    DXGI_FORMAT Format;
    UINT InputSlot;
    UINT AlignedByteOffset;
    D3D11_INPUT_CLASSIFICATION InputSlotClass;
    UINT InstanceDataStepRate;
    }
*/